### ISSUE TITLE
Conflict with com.fasterxml.jackson.databind

### ISSUE THREAD

**Issue by Allo1237217** [maxomatic458/playit-minecraft-mod#13] opened 2024-12-09 12:09 UTC
Hello im having a conflict between the playit mod and the com.fasterxml.jackson.databind please help. Here is the error:

Exception in thread "main" java.lang.module.ResolutionException: Modules playit_forge and com.fasterxml.jackson.databind export package com.fasterxml.jackson.databind to module attributefix
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

Thanks for help

**Comment by maxomatic458** [comment] 2024-12-09 13:07
@Allo1237217 can you provide some more info (full crash log file, mc version, modloader, ...)

**Comment by FreudianFondue** [comment] 2024-12-14 05:11
I'm also having this issue, as far as I can tell it's conflicting with other things that use the Jackson databind?
I've included my log below.

https://mclo.gs/lOQVBuj

**Comment by FreudianFondue** [comment] 2024-12-14 17:23
Let me know if I can help with debugging this at all, I'm in need of the mod for a server asap.

**Comment by maxomatic458** [comment] 2024-12-15 11:15
@FreudianFondue i believe its a dependency shadowing issue see #6 .
I already tried to fix that but i really wasnt getting anywhere.

Maybe use the playit program for now if possible https://playit.gg/

**Comment by maxomatic458** [comment] 2024-12-15 11:41
ill close this because its a duplicate of #6

**Closed as completed by maxomatic458** 2024-12-15 11:41 UTC
